language: node_js
node_js:
- 0.12
- iojs
before_script:
- npm install -g bower
- bower install
script:
- npm test
- npm coveralls
env:
  global:
  - secure: Ct8sEOnyRyuw3BF3IXfpRVtuBUAD1RiRvO8f08kFTBDmCiONBxeAOIJWnHaw87URmpRFUXF2j74xZyV8ISpCx6PJaxY4hkJuUzA8SzQ3P4859VLo/nKWXwAFtqEHpMis5mZaVb9G1cxfvbkrQKOImoPmUOrdbLlFnTL2/iOUMHKvheUqYv/qASK9wOmUrnzJfOrlqtwHjRytMMO9HIlSarwmdB6CtgCm/9Ichm21QyCTlMl7oc6JUX1QDXvwjZj5Jo97/SSb3uvFsCv4O1DWP7cAXEoIYahHjHRbRwwBWo3og4s2hA8IIqQl765EP7mwfLwJzlA3Ba2qXhnUjWGDOtQ5Y/OMGk+EUksJEwfgKaXjiAx2bMPFJss7EBwCc0ogz0KD89o007JIncxL067wkYQ4Ri1va2NAdSRPgu1LEzq4qQs7EpoDDZvABzKwv7VZf4WbAaw6AfPQDU7UOqQk0x2ymw3g9ZCXl1Lj8na2tl0vi0d+x3u8SLZgLCBw8Oalu4qPse2AxL82bcjzDb003uNsk+FHbZaChz3RdQw+1Q36R/n0KNu1Hvz0hD3logeAz1ZBm/CdIpas/I7Qhzw2FO+uJzrRDAPFOOgB1DQEtG+KpeyA/7tYTNfSd83Z65ZIgZVUIXL8gZx96zPWe0pptFjUVp5VmHzf3cIzhQHj+7Y=
  - secure: Ye1J8hbpq+6qSnKEr228erzPhI2r+RijEXz48rraX0t4RwU7DTX3iHOtZmjiOnQvz78Jdz4jxsvpBQ0MPGPqkYbc3z2FRM/bIzJgwypX6cCUdHCZbckzYc5zxtaICnY5ARMoto3QWfivliErtwXnZoBvamL9gzNaC9lB9+I9cwsf+TF33SaJOyJw7jhHtTWzXiCgPpatPFb0Dq6/OTS7F6A8zJYMmW15dk36Yeldaqw5a+WW4L6NYOtl5I5Q6l5dKHAoZXhJ7CBLEux6GV8GFy+c+pl71FYUjkaPBzBrAzbjfLE3oM7nzHLrX/+rD1mp6zw3TV252QDChyfXQA/jk50aND5buPu9O2mfw6ZTpi0apt7GUyoAduhIbQz+qdynotkU5LoN4LVby6gjUa55Pc2S20X5wFrstybcfmd0EMbYzYD3QqPUHO7bTSiOsVsxqVmqUR/WjcVPyeJXLI+ah3S5I4ED17p2k0jWeDwcbNFRKStIAVRuxd8VLqTqLNDCMzhH8eK0R0mzMv8ehCk1N6NlT4qGzqoQDFBn3joJ1WtzAOhsAzJguM6jN8Ted5PnNn0xaXFgtY7toMIfxs71xhl3X5FIXlMvJlfqRhHr1hfugNfZl3GdL3j3n/qYsI4NIOy9tT2FaGZ7sJAkir6J/PI2Mbvh01h/0ddMeTNUii0=
